[workspace]
members = [
  # Utilities
  "arena_alloc",

  # Public Interface
  "cli",

  # Intermediate Representations
  "ir",

  # Frontend
  "lexer",
  "parser",
  "qualifier",
  "type_checker",

  # Backend
  "flattener",
  
  # Internal
  "tests-integration"
]
