[package]
name = "tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arena_alloc = { path = "../arena_alloc" }
im = "15.1.0"
macros = { path = "../macros" }
pom = "3.4.0"
smartstring = "1.0.1"
